name: curved_animation_controller
description: The easy way to use AnimationController with Curve. Apply animation in Flutter with a more straightforward code.
version: 1.1.0+1
homepage: https://github.com/salkuadrat/curved_animation_controller
repository: https://github.com/salkuadrat/curved_animation_controller

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter